name: Resume Parser CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start FastAPI Server
      run: |
        python -m uvicorn servers.app:app --host 0.0.0.0 --port 8000 &
        # Wait up to 60 seconds for the server to start
        for i in {1..12}; do
          if curl -s http://127.0.0.1:8000/docs >/dev/null; then
            echo "Server is up!"
            exit 0
          else
            echo "Waiting for server to start..."
            sleep 5
          fi
        done
        echo "Server did not start in time." && exit 1

    - name: Test API Endpoints
      run: |
        curl -X POST "http://localhost:8000/api/staging/" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"Resume_filepath\": \"datasets/resume_files/\", \"Jobdesc_filepath\": \"datasets/job_description/\", \"Keyword\": \"Data scientist\", \"Query\": \"summarize the resume\"}"

